package scanner
package scanner

import "time"















































































}	Name  string	Scope string // Empty for unscoped packagestype CompromisedPackage struct {// CompromisedPackage represents a known malicious package}	GitReposChecked       int	WorkflowsScanned      int	FilesScanned          int	NodeModulesDirsFound  int	Findings              []Finding	CompromisedPackages   int	PathsScanned          []string	Mode                  ScanMode	Duration              time.Duration	EndTime               time.Time	StartTime             time.Timetype ScanResult struct {// ScanResult aggregates all findings and metadata from a scan}	ReportPath string	Mode       ScanMode	Roots      []stringtype ScanConfig struct {// ScanConfig holds configuration for a scan operation}	Details   string	Location  string	Indicator string	Severity  FindingSeverity	Type      FindingTypetype Finding struct {// Finding represents a single detection during the scan)	LowSeverity      FindingSeverity = "LOW"	MediumSeverity   FindingSeverity = "MEDIUM"	HighSeverity     FindingSeverity = "HIGH"	CriticalSeverity FindingSeverity = "CRITICAL"const (type FindingSeverity string// FindingSeverity indicates the risk level)	EnvAccessLowFinding    FindingType = "env-access-low"	CredentialExfilFinding FindingType = "credential-exfil"	MalwareIOCFinding      FindingType = "malware-ioc"	TruffleHogRefFinding   FindingType = "trufflehog-reference"	TruffleHogFinding      FindingType = "trufflehog-installation"	MigrationAttackFinding FindingType = "migration-attack"	MalwareHashFinding     FindingType = "malware-hash"	PostInstallHookFinding FindingType = "postinstall-hook"	RunnerInstallFinding   FindingType = "runner-installation"	MaliciousRunnerFinding FindingType = "malicious-runner"	CredentialFileFinding  FindingType = "credential-file"	WorkflowContentFinding FindingType = "workflow-content"	WorkflowPatternFinding FindingType = "workflow-pattern"	GitRemoteFinding       FindingType = "git-remote"	GitBranchFinding       FindingType = "git-branch"	FileArtefactFinding    FindingType = "file-artefact"	NPMCacheFinding        FindingType = "npm-cache"	NodeModulesFinding     FindingType = "node_modules"const (type FindingType string// FindingType categorizes the type of threat detected)	FullScan  ScanMode = "full"	QuickScan ScanMode = "quick"const (type ScanMode string// ScanMode defines the depth of scanning